http:
  port: "8081"
  private:
    port: "8091"
    
https:
  port: "8082"
  private:
    port: "8092"
    
api:
  id: "18350168"
  majorVersion: "v1"
  groupId: "62123581-121b-4c73-bf9d-19d53054fb8e"
  artifactId: "covid19-case-distribution-sapi"
  version: "1.0.0"
  specification: "resource::${api.groupId}:${api.artifactId}:${api.version}:raml:zip:covid19-case-distribution-sapi.raml"
  
caseDistributionApi:
  host: "opendata.ecdc.europa.eu"
  port: "443"
  basePath: "/covid19"
  path: "/casedistribution/csv/data.csv"
 
##Apache Active MQ 
covid19CaseDistributionQueue:
  username: "admin"
  password: "admin"
  brokerUrl: "tcp://192.168.8.126:61616"
  name: "Covid19CaseDistributionQueue"
  
##Anypoint MQ
//covid19CaseDistributionQueue:
  //name: "Covid19CaseDistributionQueue"
  //url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  //clientAppId: ""
  //clientSecret: ""

  
